project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  title: "EPortfolio"
  navbar:
    right:
      - text: About
        href: index.qmd
      - icon: github
        href: https://github.com/
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

